import{a as g,S as y,i as l}from"./assets/vendor-BMHzDZyJ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const p="50330405-e061f8fa8a72024873dc0b5e5",h="https://pixabay.com/api/";async function b(i){const r={key:p,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await g.get(h,{params:r})).data.hits}const c=document.querySelector(".gallery"),u=document.getElementById("global-loader");function L(i){const r=i.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:s,comments:m,downloads:d})=>`<li class="gallery-item"><a class="gallery-link" href="${a}"><img class="gallery-img" src="${o}" alt="${e}"></a>
  <ul class="gallery-list">
    <li class="gallery-list-item"><b>likes</b>${t}</li>
  <li class="gallery-list-item"><b>views</b>${s}</li>
  <li class="gallery-list-item"><b>comments</b>${m}</li>
  <li class="gallery-list-item"><b>downloads</b>${d}</li>
  </ul>
</li>`).join("");c.insertAdjacentHTML("beforeend",r)}function v(){c.innerHTML=""}function w(){u.classList.add("is-active")}function P(){u.classList.remove("is-active")}const f=document.querySelector(".form"),n=f.elements["search-text"],S=new y(".gallery a",{captionsData:"alt",caption:!0,captionPosition:"bottom",captionDelay:250});f.addEventListener("submit",async i=>{i.preventDefault();const r=n.value.trim();if(!r){l.info({message:"Будь ласка, введіть ключове слово!",position:"topRight",timeout:2e3,backgroundColor:"#ffa000"});return}v(),w(),b(r).then(o=>{if(!o.length){l.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3,backgroundColor:"#ef4040"});return}L(o),S.refresh(),n.value=""}).catch(()=>{l.error({title:"Error",message:"Сталася помилка. Спробуйте пізніше!",position:"topRight",timeout:3e3,backgroundColor:"#ffa040"})}).finally(()=>{P()})});
//# sourceMappingURL=index.js.map
